### ISSUE TITLE
add splendido/meteor-accounts-meld as a repository to this org

### ISSUE THREAD

**Issue by jirkadev** [meteor-compat/useraccounts-core#3]
Hi there,

would you consider adding this repository the the organisation?
https://github.com/splendido/meteor-accounts-meld

Thanks of the answer

**Comment by filipenevola** [comment]
Hi, we are using Discussions to make these decisions as explained [here](https://forums.meteor.com/t/introducing-meteor-compat-packages/56759).

Could you open a [new discussion](https://github.com/meteor/meteor/discussions/new)? Thanks.
