### ISSUE TITLE
Error when logging in with username only

### ISSUE THREAD

**Issue by BoThomas** [meteor-compat/useraccounts-core#4]
Hi!

I updated an old project to a newer meteor version and many packages with it.
I've since got a problem with "useraccounts-core" when trying to login with an username.

I think i found the bug in server.js in line 126:

`var loginEmail = attempt.methodArguments[0].user.email.toLowerCase();`
`if (loginEmail) {`

"attempt.methodArguments[0].user.email" is undefined when logging in only with an username. 
This is handled inside the else-branch starting from line 134.

But as "toLowerCase()" is called before the check in line 127, there is an TypeError: Cannot read property 'toLowerCase' of undefined.

I fixed this issue locally with moving the "toLowerCase()" inside the if-statement.
`var loginEmail = attempt.methodArguments[0].user.email;`
`if (loginEmail) {`
`loginEmail = loginEmail.toLowerCase();`

Greetings Thomas

**Comment by BoThomas** [comment]
I've created a [Pull-Request](https://github.com/meteor-compat/useraccounts-core/pull/6) with an easy fix.

**Comment by filipenevola** [comment]
useraccounts:core@1.16.2 published with this fix.
